# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af173a865e6e5426a1667c128ba8e97892f6ad3164499d8756be983e9a0792b45ebda6f4931e384558abed6cf6e49ffb8329c2199665f156b6cb5ce0dcb8b16d

test:
  secret_key_base: 31fa10702307bd06fd88ebd7eb785c5cde1fbc4aac478c53163ef41c7386daf473ed3c8e7065304a03c1e1d4d8f5445132a47b6f68daf879c9b1bcef72fa8d7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
